module Fluent::Plugin::OpenMetrics::Input
  API_VERSION="v1"

  K8S_RESOURCE_KIND_POD="Pod"
  K8S_RESOURCE_KIND_NODE="Node"
  K8S_RESOURCE_KIND_SERVICE="Service"
  K8S_RESOURCE_KIND_ENDPOINT="Endpoint"

  K8S_RESOURCE_TYPE_PODS="Pods"
  K8S_RESOURCE_TYPE_NODES="Nodes"
  K8S_RESOURCE_TYPE_SERVICES="Services"
  K8S_RESOURCE_TYPE_ENDPOINTS="Endpoints"

  RESOURCE_TYPE_PODS="pods"
  RESOURCE_TYPE_NODES="nodes"
  RESOURCE_TYPE_SERVICES="services"
  RESOURCE_TYPE_ENDPOINTS="endpoints"

  SUCCESS_RESPONSE = "200"
end
