#!/bin/sh
export GEM_HOME="/opt/unified-monitoring-agent/embedded/lib/ruby/gems/3.0.0/"
export GEM_PATH="/opt/unified-monitoring-agent/embedded/lib/ruby/gems/3.0.0/"
/opt/unified-monitoring-agent/embedded/bin/fluent-gem "$@"
