# -*- encoding: utf-8 -*-
# stub: hydra_pika_client 1.2 ruby lib

Gem::Specification.new do |s|
  s.name = "hydra_pika_client".freeze
  s.version = "1.2"

  s.required_rubygems_version = Gem::Requirement.new(">= 0".freeze) if s.respond_to? :required_rubygems_version=
  s.require_paths = ["lib".freeze]
  s.authors = ["Hydra/Lumberjack Team".freeze, "John Feiler".freeze]
  s.date = "2022-10-15"
  s.description = "Internal use autogenerated client for Hydra Pika Frontend for Lumberjack".freeze
  s.email = ["hydra_dev_us_grp@oracle.com".freeze, "john.feiler@oracle.com".freeze]
  s.homepage = "https://confluence.oci.oraclecorp.com/display/LUM/".freeze
  s.licenses = ["UPL-1.0".freeze, "Apache-2.0".freeze]
  s.required_ruby_version = Gem::Requirement.new(">= 2.2.0".freeze)
  s.rubygems_version = "3.2.33".freeze
  s.summary = "Hydra Pika Ruby Client".freeze

  s.installed_by_version = "3.2.33" if s.respond_to? :installed_by_version

  if s.respond_to? :specification_version then
    s.specification_version = 4
  end

  if s.respond_to? :add_runtime_dependency then
    s.add_runtime_dependency(%q<oci>.freeze, [">= 2"])
  else
    s.add_dependency(%q<oci>.freeze, [">= 2"])
  end
end
